services:
  postgres-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reforest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d reforest_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres_db_reforest

  mongo-db:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: reforest_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    container_name: mongo_db_reforest

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth-service # Assumes a multi-stage Dockerfile with a stage named 'auth-service'
    restart: on-failure
    ports:
      - "50051:50051"
    env_file:
      - .env.docker
    depends_on:
      postgres-db:
        condition: service_healthy

  tree-management-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: tree-management-service # Assumes a multi-stage Dockerfile
    restart: on-failure
    ports:
      - "50052:50052"
    env_file:
      - .env.docker
    depends_on:
      - mongo-db

  finance-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: finance-service
    restart: on-failure
    ports:
      - "50053:50053"
    env_file:
      - .env.docker
    depends_on:
      postgres-db:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      # Assumes a Dockerfile in your project root that can build the api gateway
      dockerfile: Dockerfile
      target: api-gateway # Assumes a multi-stage Dockerfile with a stage named 'api-gateway'
    restart: on-failure
    ports:
      - "8080:8080" # Assuming your API gateway listens on port 8080
    depends_on:
      - auth-service
      - tree-management-service
      - finance-service
    env_file:
      - .env.docker

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq_reforest

volumes:
  postgres_data:
  mongo_data:
